// Trainer
export const GET_TRAINER = "GET_TRAINER";
export const ADD_TRAINER = "ADD_TRAINER";
export const DELETE_TRAINER = "DELETE_TRAINER";
export const ADD_POKEMON_TO_TRAINER = "ADD_POKEMON_TO_TRAINER";
export const REMOVE_POKEMON_FROM_TRAINER = "REMOVE_POKEMON_FROM_TRAINER";

// Pokemon
export const GET_POKEMON = "GET_POKEMON";
export const ASSIGN_POKEMON = "ASSIGN_POKEMON";
export const RELEASE_POKEMON = "RELEASE_POKEMON";
